sudo: false
language: node_js
node_js:
  - 8
  - 10
  - 12
  - 14
  - node
script:
  - yarn install --non-interactive
  - yarn lint
notifications:
  email:
    on_success: never
    on_failure: always
